print('hello world')
answer = input("a stranger walks up to you. what do you say?")
if answer == "hello": print("the stranger says hello back.")
elif answer == "hi": print("the stranger says hello back.")
else: print("the stranger gets mad at your improper greeting, and shoots you. you die from a gunshot wound."); quit() 
answer = input("now the stranger tells you to come with him to his horse. do you join him or not?")
if answer == "yes": print("you follow him to his horse.")
else: print("the stranger does not take no for a answer, so you eventually cave in and go along.")
print("the stranger tells you his name is Richard as you walk along.")
answer = input("Richard tells you he needs your help.\n if you help him, he will reward you.\n do you agree to help him? \n agree, or refuse \n")
if answer == "agree": print("Richard is delighted, and tells you to go get your horse.")
elif answer == "refuse": print("Richard sighs and lets you walk back to the tavern,\n but you have a feeling you just missed out on something\n THE END"); quit() 
else: print("Richard gets mad becuase of your indesicion, and shoots you. you die."); quit() 
print("you get on your horse, and the two of you start riding together\n END OF CHAPTER ONE \n")